[package]
name = "babback"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tts = "0.17"
ctrlc = "3"
rand = "0.8"
